heat_template_version: 2016-04-08

description:
  Deploys an APACHE 2 instance attached to private network

parameters:
  name:
    type: string
    default: apache
  image_id:
    type: string
    default: Xenial
  flavor:
    type: string
    default: my_flavor
  key_name:
    type: string
    default: MyKeyPair

resources:
  instance:
    type: OS::Nova::Server
    properties:
      name: { get_param: name }
      image: { get_param: image_id }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - network: private    
      user_data_format: RAW
      user_data:
        str_replace:
          params:
            wc_notify: {  }
          template: |
            #!/bin/bash            
            set -e 
            set -o pipefail
            sudo apt-get clean
            sudo apt-get update
            sudo apt-get -y upgrade
            sudo apt-get -y install apache2 htop stress
            sudo ufw allow 'Apache Full'
            sudo chmod -R 777 /var/www/html
            sudo cat <<EOF > /var/www/html/index.html
            <html><body><title>Apache Server - $(hostname)</title></body></html>
            EOF